// ============================================
// FLASHCARDS — CONAMAT: Ciencias de la Salud y Premedicina
// Basadas en la Guía EXANI-II CONAMAT pp. 605-646
// Unidad 1: Proceso Salud-Enfermedad
// Unidad 2: Morfofisiología del cuerpo humano
// ============================================

const FLASHCARDS_CONAMAT = [

// ── TERMINOLOGÍA DE CIENCIAS DE LA SALUD ─────────────
{ id:'cm1', modulo:'Terminología Salud', frente:'¿Qué es un accidente cerebrovascular?', reverso:'Interrupción del flujo sanguíneo hacia el cerebro, ya sea por una hemorragia o un coágulo. Provoca problemas para hablar, entender, ver, y dolor de cabeza súbito.', color:'#ef4444', icono:'🧠' },
{ id:'cm2', modulo:'Terminología Salud', frente:'¿Qué es un agente causal?', reverso:'Sustancia, mezcla, forma de energía u organismo que, al entrar en contacto con el ser humano bajo ciertas condiciones ambientales, puede provocar o mantener un proceso patológico.', color:'#ef4444', icono:'🦠' },
{ id:'cm3', modulo:'Terminología Salud', frente:'¿Qué es la arritmia cardíaca?', reverso:'Alteración de la frecuencia cardíaca (pulso) o del ritmo cardíaco.\n• Taquicardia: corazón late muy rápido\n• Bradicardia: corazón late muy lento\n• También puede latir de forma irregular.', color:'#ef4444', icono:'❤️' },
{ id:'cm4', modulo:'Terminología Salud', frente:'¿Qué es la biometría hemática (hemograma)?', reverso:'Estudio que determina la concentración de eritrocitos, leucocitos y plaquetas. Estudia el estado genérico de las células y proporciona información confiable del estado general de salud del paciente.', color:'#ef4444', icono:'🩸' },
{ id:'cm5', modulo:'Terminología Salud', frente:'¿Qué es la cetoacidosis?', reverso:'Se presenta cuando el cuerpo no puede usar glucosa para producir energía y recurre a los lípidos, produciendo cetonas como subproductos, lo que provoca una disminución en el pH de la sangre.', color:'#ef4444', icono:'⚗️' },
{ id:'cm6', modulo:'Terminología Salud', frente:'¿Qué es la diástole?', reverso:'Dilatación de las arterias y relajación del corazón que permite que la sangre ingrese hacia las aurículas. Es la fase de llenado del corazón. (Contracción = sístole)', color:'#ef4444', icono:'❤️' },
{ id:'cm7', modulo:'Terminología Salud', frente:'¿Qué es la homeostasis?', reverso:'Sistema de fenómenos de autorregulación que permiten mantener un equilibrio de concentraciones, propiedades y funciones orgánicas. Es el equilibrio interno del organismo.', color:'#ef4444', icono:'⚖️' },
{ id:'cm8', modulo:'Terminología Salud', frente:'¿Qué es la morbilidad?', reverso:'Número de personas que enferman en un lugar y momento determinados. Indica la FRECUENCIA de enfermedad en una población. (No confundir con mortalidad = muertes)', color:'#ef4444', icono:'📊' },
{ id:'cm9', modulo:'Terminología Salud', frente:'¿Diferencia entre pandemia, epidemia y endemia?', reverso:'• ENDEMIA: enfermedad persistente en una región concreta\n• EPIDEMIA: aumento inusual de casos en una región\n• PANDEMIA: difusión de una enfermedad a distintos países o a nivel planetario', color:'#ef4444', icono:'🌍' },
{ id:'cm10', modulo:'Terminología Salud', frente:'¿Qué es el síndrome?', reverso:'Conjunto de signos y síntomas que concurren en espacio y tiempo, cuyas causas son variadas. Ej: síndrome metabólico (hipertensión + obesidad + hiperglucemia).', color:'#ef4444', icono:'📋' },
{ id:'cm11', modulo:'Terminología Salud', frente:'¿Diferencia entre síntoma y signo?', reverso:'• SÍNTOMA: subjetivo, lo que el paciente REFIERE sentir (dolor, malestar, náusea)\n• SIGNO: objetivo, lo que el médico OBJETIVA en exploración física (fiebre medida, ictericia, taquicardia al pulso)', color:'#ef4444', icono:'🩺' },
{ id:'cm12', modulo:'Terminología Salud', frente:'¿Qué es la patogenicidad vs el poder antigénico?', reverso:'• PATOGENICIDAD: capacidad de un agente para provocar una enfermedad en el huésped\n• PODER ANTIGÉNICO: capacidad de un agente para producir una respuesta inmune en los huéspedes', color:'#ef4444', icono:'🛡️' },

// ── TRÍADA ECOLÓGICA ─────────────────────────────────
{ id:'cm13', modulo:'Tríada Ecológica', frente:'¿Qué es la tríada ecológica o epidemiológica?', reverso:'La convergencia de los TRES factores necesarios para que se desarrolle una enfermedad:\n1. AGENTE (extrínseco o intrínseco)\n2. HUÉSPED (especie, edad, sexo, resistencia)\n3. AMBIENTE (químico, físico, biológico, social)', color:'#8b5cf6', icono:'🔺' },
{ id:'cm14', modulo:'Tríada Ecológica', frente:'¿Cómo se clasifican los agentes patógenos?', reverso:'• FÍSICOS: temperaturas extremas, radiación solar\n• QUÍMICOS: contaminantes industriales, elementos químicos naturales en altas concentraciones\n• BIOLÓGICOS: bacterias, hongos, protozoos, virus\n• SOCIALES: falta de higiene, pobreza, mala alimentación', color:'#8b5cf6', icono:'🦠' },
{ id:'cm15', modulo:'Tríada Ecológica', frente:'¿Características de las bacterias como agentes biológicos?', reverso:'• Organismos microscópicos unicelulares SIN núcleo definido (procariotas)\n• Morfología variada\n• Se multiplican por fisión binaria\n• Provocan enfermedades por las toxinas que producen\n• Se tratan con antibióticos', color:'#8b5cf6', icono:'🦠' },
{ id:'cm16', modulo:'Tríada Ecológica', frente:'¿Características de los virus como agentes biológicos?', reverso:'• NO están formados por células\n• Estructura básica: cápside de proteínas que contiene ADN o ARN\n• Para replicarse DEBEN invadir células\n• Muestran especificidad por ciertos tejidos\n• Las infecciones son autolimitantes', color:'#8b5cf6', icono:'🦠' },

// ── HISTORIA NATURAL DE LA ENFERMEDAD ────────────────
{ id:'cm17', modulo:'Historia Natural', frente:'¿Cuáles son las etapas de la historia natural de la enfermedad?', reverso:'1. PREPATOGÉNICA (incubación): sin síntomas, contacto con agente\n2. PATOGÉNICA: aparecen síntomas. Incluye: periodo subclínico → horizonte clínico → periodo clínico\n3. DE RESOLUCIÓN: recuperación, curación con secuelas, o muerte', color:'#10b981', icono:'📈' },
{ id:'cm18', modulo:'Historia Natural', frente:'¿Qué ocurre en la etapa prepatogénica?', reverso:'El individuo NO manifiesta síntomas y aparentemente está sano, pero ya entró en contacto con el agente patógeno. El sistema inmune puede eliminar al agente y evitar la siguiente etapa, o progresar a la patogénica.', color:'#10b981', icono:'📈' },
{ id:'cm19', modulo:'Historia Natural', frente:'¿Qué es el horizonte clínico?', reverso:'Línea dentro de la etapa patogénica que marca cuando surgen los síntomas CARACTERÍSTICOS de la enfermedad. Antes del horizonte: periodo subclínico (respuesta inicial del organismo). Después: periodo clínico (cambios reconocibles en la apariencia del paciente).', color:'#10b981', icono:'📈' },
{ id:'cm20', modulo:'Historia Natural', frente:'¿Qué es la etapa de resolución?', reverso:'Consecuencias finales de la enfermedad, que pueden ser:\n• Recuperación total\n• Curación con secuelas\n• Muerte\nDepende de si la intervención médica fue oportuna.', color:'#10b981', icono:'📈' },

// ── NIVELES DE PREVENCIÓN ─────────────────────────────
{ id:'cm21', modulo:'Niveles de Prevención', frente:'¿En qué consiste la prevención PRIMARIA?', reverso:'Actúa ANTES de que la enfermedad ocurra. Basada en:\n• Campañas informativas\n• Educación para la salud\n• Evitar la automedicación\n• Vacunas, buena alimentación, saneamiento\nEjemplos: lavarse las manos, usar preservativos, vacunarse', color:'#f59e0b', icono:'🛡️' },
{ id:'cm22', modulo:'Niveles de Prevención', frente:'¿En qué consiste la prevención SECUNDARIA?', reverso:'Diagnóstico TEMPRANO y apego al tratamiento. Busca:\n• Limitar el daño de la enfermedad\n• Implementar tratamiento adecuado\n• Evitar complicaciones\n• Disminuir la mortalidad\nCarácter preventivo Y curativo', color:'#f59e0b', icono:'🛡️' },
{ id:'cm23', modulo:'Niveles de Prevención', frente:'¿En qué consiste la prevención TERCIARIA?', reverso:'Se aplica al final de la sintomatología. Basada en REHABILITACIÓN para:\n• Recuperar funciones perdidas\n• Permitir la reinserción social y laboral\nEjemplo: rehabilitación tras embolia cerebral para recuperar el habla o la marcha', color:'#f59e0b', icono:'🛡️' },

// ── SIGNOS VITALES ────────────────────────────────────
{ id:'cm24', modulo:'Signos Vitales', frente:'¿Cuáles son los rangos normales de los signos vitales?', reverso:'• Presión arterial: 90/60 a 120/80 mmHg\n• Respiración: 12 a 18 respiraciones por minuto\n• Pulso: 60 a 100 latidos por minuto\n• Temperatura: 36.5°C a 37.3°C (promedio 37°C)', color:'#06b6d4', icono:'🩺' },
{ id:'cm25', modulo:'Signos Vitales', frente:'¿Qué es la semiología clínica?', reverso:'Disciplina médica que se ocupa de:\n• Identificar manifestaciones patológicas (signos y síntomas)\n• Buscarlas mediante semiotecnia\n• Agruparlas y clasificarlas como síndromes o enfermedades\n• Interpretarlas para formular el diagnóstico', color:'#06b6d4', icono:'🩺' },
{ id:'cm26', modulo:'Signos Vitales', frente:'¿Cómo se obtienen los signos en exploración física?', reverso:'A través de:\n• INSPECCIÓN\n• AUSCULTACIÓN\n• PERCUSIÓN\n• PALPACIÓN\n• ECOGRAFÍA (ultrasonido o POCUS - Point of Care Ultrasound)', color:'#06b6d4', icono:'🩺' },

// ── MICROBIOLOGÍA Y PARASITOLOGÍA ─────────────────────
{ id:'cm27', modulo:'Microbiología', frente:'¿Qué es el parasitismo?', reverso:'Asociación donde un ser vivo (parásito) se aloja en otro organismo de especie distinta (huésped u hospedero), obtiene nutrientes y le causa daños pudiendo provocarle la muerte.', color:'#84cc16', icono:'🔬' },
{ id:'cm28', modulo:'Microbiología', frente:'¿Tipos de huésped según el parasitismo?', reverso:'• INTERMEDIARIO: el parásito desarrolla sus etapas juveniles (desde larva)\n• DEFINITIVO: el parásito desarrolla su etapa adulta\n• PARATÉNICO: sirve como refugio temporal para acceder al huésped definitivo', color:'#84cc16', icono:'🔬' },
{ id:'cm29', modulo:'Microbiología', frente:'¿Diferencia entre infección parasitaria y enfermedad parasitaria?', reverso:'• INFECCIÓN PARASITARIA: el hospedero presenta parásitos pero NO manifiesta síntomas → portador sano\n• ENFERMEDAD PARASITARIA: el huésped SÍ presenta alteraciones patológicas con sintomatología', color:'#84cc16', icono:'🔬' },
{ id:'cm30', modulo:'Microbiología', frente:'¿Cuáles son las enfermedades parasitarias comunes?', reverso:'• Giardiasis (Giardia intestinalis): evacuaciones grasosas, cólicos\n• Malaria (Plasmodium): fiebre, escalofríos, ictericia\n• Cisticercosis (Taenia solium): quistes, convulsiones, afección cerebral\n• Ascariasis (Ascaris lumbricoides): neumonía eosinofílica, dolor estomacal', color:'#84cc16', icono:'🔬' },

// ── FARMACOLOGÍA ──────────────────────────────────────
{ id:'cm31', modulo:'Farmacología', frente:'¿Qué es un fármaco?', reverso:'Cualquier sustancia química que pueda interactuar con el organismo para realizar un tratamiento, prevención, curación o diagnóstico de una enfermedad. Es el principio activo de un medicamento.', color:'#a78bfa', icono:'💊' },
{ id:'cm32', modulo:'Farmacología', frente:'¿Cuáles son las ramas de la farmacología?', reverso:'• FARMACODINAMIA: cómo influyen las drogas en procesos fisiológicos y bioquímicos\n• FARMACOCINÉTICA: absorción, distribución, metabolismo y excreción\n• FARMACOLOGÍA TERAPÉUTICA: aplicación de medicamentos a enfermedades\n• TOXICOLOGÍA: intoxicaciones\n• FARMACOGNOSIA: origen natural de drogas', color:'#a78bfa', icono:'💊' },
{ id:'cm33', modulo:'Farmacología', frente:'¿Etapas del desarrollo de un nuevo medicamento?', reverso:'1. ESTUDIOS PRECLÍNICOS: tamizaje y bioensayo (en animales)\n2. ENSAYOS CLÍNICOS: Fase I, II y III (en humanos)\n3. APROBACIÓN por unidad reguladora\n4. FASE 4: farmacovigilancia, estudios de utilización\n→ Aprobación definitiva', color:'#a78bfa', icono:'💊' },
{ id:'cm34', modulo:'Farmacología', frente:'¿Clasificación de fármacos por uso?', reverso:'• Analgésicos: alivian el dolor (opiáceos y no-opiáceos/AINE)\n• Antiácidos: reducen la acidez gástrica\n• Antialérgicos: combaten reacciones alérgicas (antihistamínicos)\n• Antiinfecciosos: antibióticos, antifúngicos, antivirales, antiparasitarios\n• Antipiréticos: reducen fiebre (aspirina, ibuprofeno, paracetamol)', color:'#a78bfa', icono:'💊' },
{ id:'cm35', modulo:'Farmacología', frente:'¿Vías de administración de medicamentos?', reverso:'• EXTERNA: piel, mucosas (nasal, uretral, vaginal, conjuntival), oído, orofaringe\n• INTERNA: entérica (oral, sublingual, rectal) y parenteral (inyecciones: intradérmica, subcutánea, intramuscular, endovenosa, intratecal) e inhalatoria\n• PERCUTÁNEA: a través de la piel para actuar en otro sitio', color:'#a78bfa', icono:'💊' },

// ── CONDUCTAS DE RIESGO ───────────────────────────────
{ id:'cm36', modulo:'Conductas de Riesgo', frente:'¿Qué son las conductas de riesgo?', reverso:'Características o circunstancias que incrementan la probabilidad de daño a la salud. Las más comunes: tabaquismo, drogadicción, alcoholismo, exposición a ambientes peligrosos y violentos, mala nutrición, actividad sexual precoz.', color:'#f97316', icono:'⚠️' },
{ id:'cm37', modulo:'Conductas de Riesgo', frente:'¿Qué es el IMC y cuáles son sus rangos?', reverso:'IMC = Masa corporal (kg) / (Estatura en m)²\n• <16: Desnutrición\n• 17-20: Delgadez\n• 20-25: Normal\n• 25-30: Sobrepeso\n• 30-35: Sobrepeso crónico\n• 35-40: Obesidad premórbida\n• >40: Obesidad mórbida', color:'#f97316', icono:'⚠️' },
{ id:'cm38', modulo:'Conductas de Riesgo', frente:'¿Cuáles son las situaciones de emergencia?', reverso:'Suceso que tiene 3 condiciones: no controlado y de riesgo considerable, produce daños o lesiones, requiere actuación de un grupo organizado. Ejemplos: incendios, sismos, inundaciones, huracanes, tsunamis, erupciones volcánicas, accidentes.', color:'#f97316', icono:'🚨' },
{ id:'cm39', modulo:'Conductas de Riesgo', frente:'¿Cuáles son los tipos de desastres?', reverso:'• NATURALES o SOCIO-NATURALES:\n  - Meteorológicos (atmósfera y clima)\n  - Topográficos y geotécnicos (superficie terrestre)\n  - Tectónicos o geológicos (capas internas de la Tierra)\n• ANTROPOLÓGICOS y SOCIALES:\n  - Exclusión humana, guerras, malagestión, accidentes', color:'#f97316', icono:'🚨' },

// ── SISTEMAS DE REFERENCIA ANATÓMICA ─────────────────
{ id:'cm40', modulo:'Planimetría Anatómica', frente:'¿Cuáles son las regiones del cuerpo humano?', reverso:'• CABEZA: cráneo y cara\n• TRONCO: tórax, abdomen y pelvis\n• EXTREMIDADES: superiores (brazos) e inferiores (piernas)\n\nPrincipales cavidades: craneal, torácica, abdominal, pélvica', color:'#6366f1', icono:'📐' },
{ id:'cm41', modulo:'Planimetría Anatómica', frente:'¿Qué contiene cada cavidad del cuerpo?', reverso:'• CRANEAL: encéfalo\n• TORÁCICA: pulmones y corazón\n• ABDOMINAL: estómago, intestinos, hígado, páncreas, bazo, riñones\n• PÉLVICA: vejiga urinaria, útero, ovarios\n(Separadas por el diafragma entre torácica y abdominal)', color:'#6366f1', icono:'📐' },
{ id:'cm42', modulo:'Planimetría Anatómica', frente:'¿Cuáles son los planos anatómicos?', reverso:'• SAGITAL: divide cuerpo en mitad izquierda y derecha\n• FRONTAL (coronal): divide en anterior/ventral y posterior/dorsal\n• TRANSVERSAL (horizontal): divide en mitad superior/cefálica e inferior/caudal', color:'#6366f1', icono:'📐' },
{ id:'cm43', modulo:'Planimetría Anatómica', frente:'¿Qué significa cada término direccional anatómico?', reverso:'• Superior/Inferior: posición hacia la cabeza/alejado de ella\n• Anterior/Posterior: parte frontal/trasera\n• Medial/Lateral: cerca/lejos de la línea media\n• Superficial/Profundo: en superficie/lejos de ella\n• Proximal/Distal: cerca/lejos del origen de un miembro', color:'#6366f1', icono:'📐' },

// ── TEJIDOS DEL CUERPO HUMANO ─────────────────────────
{ id:'cm44', modulo:'Tejidos', frente:'¿Cuáles son los 4 tipos de tejidos del cuerpo humano?', reverso:'a) EPITELIAL: excreción, secreción, protección, absorción\nb) CONJUNTIVO Y DE SOSTÉN: soporte y relleno (macrófagos, plasmocitos, adipocitos)\nc) MUSCULAR: contracción (liso, estriado, cardíaco)\nd) NERVIOSO: recibir estímulos, transmitir sensaciones (neurona como unidad)', color:'#14b8a6', icono:'🔬' },
{ id:'cm45', modulo:'Tejidos', frente:'¿Tipos de tejido muscular y sus características?', reverso:'• LISO: contracción INVOLUNTARIA, movimientos lentos. Ej: intestino\n• ESTRIADO: contracción VOLUNTARIA, multinucleado. Ej: músculos de extremidades\n• CARDÍACO: semejante al estriado, pero contracción INVOLUNTARIA rápida. Exclusivo del corazón', color:'#14b8a6', icono:'🔬' },
{ id:'cm46', modulo:'Tejidos', frente:'¿Cuáles son las partes de la neurona?', reverso:'• SOMA (cuerpo celular): contiene el núcleo\n• DENDRITAS: reciben los impulsos nerviosos (hacia el soma)\n• AXÓN: transmite los impulsos (desde el soma)\n• PIE: terminal del axón donde ocurre la sinapsis\nLas fibras nerviosas son conjuntos de axones protegidos por mielina', color:'#14b8a6', icono:'🔬' },

// ── ÓRGANOS PRINCIPALES ───────────────────────────────
{ id:'cm47', modulo:'Órganos Principales', frente:'¿Cuál es la estructura y función del corazón?', reverso:'Órgano muscular hueco con 4 cámaras:\n• 2 AURÍCULAS: reciben la sangre que llega\n• 2 VENTRÍCULOS: impulsan la sangre hacia el cuerpo (izq) y pulmones (der)\nSístole = contracción (impulsa sangre)\nDiástole = relajación (se llena de sangre)', color:'#ef4444', icono:'❤️' },
{ id:'cm48', modulo:'Órganos Principales', frente:'¿Cuáles son los grupos sanguíneos y la compatibilidad?', reverso:'Tipos: A, B, AB, O (con factor Rh + o -)\n• DONADOR UNIVERSAL: O-\n• RECEPTOR UNIVERSAL: AB+\nLa incompatibilidad causa hemólisis, anemia, fallo renal, shock o muerte.', color:'#ef4444', icono:'🩸' },
{ id:'cm49', modulo:'Órganos Principales', frente:'¿Qué son los pulmones y cómo están organizados?', reverso:'Pulmón derecho: 3 lóbulos (superior, medio, inferior)\nPulmón izquierdo: 2 lóbulos (superior e inferior)\nCubiertos por la pleura visceral (interna) y parietal (externa)\nEl intercambio de gases (hematosis) ocurre en los ALVÉOLOS', color:'#38bdf8', icono:'🫁' },
{ id:'cm50', modulo:'Órganos Principales', frente:'¿Cuál es la estructura del cerebro?', reverso:'Divido por la fisura interhemisférica en hemisferio derecho e izquierdo:\n• L. FRONTAL: pensamiento abstracto, movimiento, juicio\n• L. PARIETAL: estímulos sensoriales, orientación espacial\n• L. OCCIPITAL: área visual\n• L. TEMPORAL: región auditiva, memoria\n• CUERPO CALLOSO: conecta los hemisferios', color:'#8b5cf6', icono:'🧠' },
{ id:'cm51', modulo:'Órganos Principales', frente:'¿Cuáles son las glándulas endocrinas y sus hormonas?', reverso:'• HIPÓFISIS: GH, prolactina, oxitocina, TSH, FSH, LH\n• SUPRARRENALES: adrenalina, noradrenalina, aldosterona, cortisol\n• PÁNCREAS: insulina (células β), glucagón (células α)\n• TIROIDES: tiroxina (metabolismo), calcitonina (calcio)\n• PINEAL: melatonina (ritmos circadianos)', color:'#10b981', icono:'⚗️' },
{ id:'cm52', modulo:'Órganos Principales', frente:'¿Estructura y función del riñón?', reverso:'Forma de haba, ubicados en la parte posterior del abdomen.\nUnidad funcional: NEFRONA (regula concentración, volumen y pH de sangre)\nFiltran ~200 L de sangre/día → producen ~2 L de orina\nOrina baja por URÉTERES → VEJIGA → URETRA al exterior', color:'#f59e0b', icono:'🫀' },

// ── SISTEMAS DEL CUERPO HUMANO ────────────────────────
{ id:'cm53', modulo:'Sistemas del Cuerpo', frente:'¿Componentes del sistema digestivo?', reverso:'Boca → Faringe → Esófago → Estómago → Intestino delgado (duodeno, yeyuno, íleon) → Intestino grueso → Recto\nÓrganos accesorios: hígado (bilis), páncreas (enzimas), vesícula biliar\nFunción: digestión y absorción de nutrientes', color:'#f59e0b', icono:'🫀' },
{ id:'cm54', modulo:'Sistemas del Cuerpo', frente:'¿Cuáles son los componentes del sistema nervioso central?', reverso:'ENCÉFALO:\n• Bulbo raquídeo: centros cardíacos, respiratorio, reflejos\n• Mesencéfalo: impulsos visuales y auditivos\n• Tálamo: relevo e interpretación de impulsos\n• Hipotálamo: temperatura, apetito, sed, sueño\n• Cerebelo: equilibrio y coordinación\n• Cerebro: funciones superiores\n+ MÉDULA ESPINAL: conducción de reflejos', color:'#8b5cf6', icono:'🧠' },
{ id:'cm55', modulo:'Sistemas del Cuerpo', frente:'¿Función de cada parte del encéfalo?', reverso:'• BULBO RAQUÍDEO: corazón, respiración, vasoconstricción, reflejos (tos, hipo, parpadeo)\n• TÁLAMO: conscientes del dolor\n• HIPOTÁLAMO: vísceras, temperatura corporal, apetito, sed, sueño y alerta\n• CEREBELO: equilibrio, postura y tono muscular\n• CEREBRO: pensamiento, memoria, lenguaje, emociones', color:'#8b5cf6', icono:'🧠' },
{ id:'cm56', modulo:'Sistemas del Cuerpo', frente:'¿Qué produce cada parte del aparato reproductor masculino?', reverso:'• TESTÍCULOS: espermatozoides + testosterona/andrógenos\n• TÚBULOS SEMINÍFEROS: producen espermatozoides\n• EPIDÍDIMO: madura y almacena espermatozoides\n• CONDUCTOS DEFERENTES: transportan espermatozoides\n• VESÍCULA SEMINAL + PRÓSTATA: producen líquido seminal\n• URETRA: transporta semen y orina al exterior', color:'#ec4899', icono:'🧬' },
{ id:'cm57', modulo:'Sistemas del Cuerpo', frente:'¿Cuál es la función de cada parte del aparato reproductor femenino?', reverso:'• OVARIOS: producen óvulos y hormonas (progesterona y estrógenos)\n• TROMPAS DE FALOPIO: conducen el óvulo al útero; sitio de fecundación\n• ÚTERO: contiene endometrio; donde se implanta el embrión\n• VAGINA: copulación y conducto del parto\n• VULVA: protección de entrada vaginal', color:'#ec4899', icono:'🧬' },
{ id:'cm58', modulo:'Sistemas del Cuerpo', frente:'¿Cuál es el sistema óseo y cuántos huesos tiene?', reverso:'206 huesos divididos en:\n• ESQUELETO AXIAL (80): cabeza (cráneo+cara), cuello y tronco (columna vertebral, costillas, esternón)\n• ESQUELETO APENDICULAR (126): extremidades superiores (64) e inferiores (62)\nFunción: sostén, forma, protección, inserción muscular y producción de células sanguíneas', color:'#f97316', icono:'🦴' },

// ── SENTIDOS ──────────────────────────────────────────
{ id:'cm59', modulo:'Órganos de los Sentidos', frente:'¿Cuáles son las tres partes del oído y su función?', reverso:'• OÍDO EXTERNO: pabellón auditivo + conducto externo → dirige ondas sonoras\n• OÍDO MEDIO: tímpano + huesecillos (martillo, yunque, estribo) → amplifica vibraciones\n• OÍDO INTERNO: caracol, vestíbulo, canales semicirculares → transforma en impulsos nerviosos + equilibrio', color:'#06b6d4', icono:'👂' },
{ id:'cm60', modulo:'Órganos de los Sentidos', frente:'¿Cuáles son las capas del ojo y su función?', reverso:'• ESCLERÓTICA: protección (5/6 de la superficie ocular)\n• CAPA MEDIA o ÚVEA: coroides, cuerpo ciliar e iris\n• RETINA: membrana sensible a la luz\nFunción general: convertir ondas electromagnéticas de la luz en impulsos nerviosos → nervio óptico → cerebro', color:'#06b6d4', icono:'👁️' },

];

// Exportar para uso en el sistema
if (typeof module !== 'undefined') module.exports = FLASHCARDS_CONAMAT;
