// ============================================
// FLASHCARDS — MEDIPREP SMART
// Tarjetas de memorización por módulo
// ============================================

const FLASHCARDS_DATA = [

// ── PLANIMETRÍA ──────────────────────────────────────
{ id:'fc1', modulo:'Planimetría', frente:'¿Qué divide el plano sagital?', reverso:'Divide el cuerpo en mitad DERECHA e IZQUIERDA.\nSi pasa por la línea media exacta = plano mediosagital.', color:'#6366f1', icono:'📐' },
{ id:'fc2', modulo:'Planimetría', frente:'¿Qué divide el plano coronal o frontal?', reverso:'Divide el cuerpo en parte ANTERIOR (ventral) y POSTERIOR (dorsal).', color:'#6366f1', icono:'📐' },
{ id:'fc3', modulo:'Planimetría', frente:'¿Qué divide el plano transversal o axial?', reverso:'Divide el cuerpo en parte SUPERIOR (craneal) e INFERIOR (caudal).\nEs perpendicular al eje longitudinal.', color:'#6366f1', icono:'📐' },
{ id:'fc4', modulo:'Planimetría', frente:'¿Cuál es la diferencia entre medial y lateral?', reverso:'MEDIAL = más cercano a la línea media.\nLATERAL = más alejado de la línea media.\nEj: la nariz es medial, las orejas son laterales.', color:'#6366f1', icono:'📐' },
{ id:'fc5', modulo:'Planimetría', frente:'¿Qué significa proximal vs distal?', reverso:'PROXIMAL = más cerca del origen de un miembro.\nDISTAL = más lejos del origen.\nEj: el codo es proximal a la muñeca; los dedos son distales.', color:'#6366f1', icono:'📐' },
{ id:'fc6', modulo:'Planimetría', frente:'¿Qué es el plano de Frankfurt?', reverso:'Plano horizontal de referencia craneométrico que une el borde inferior de la órbita con el borde superior del meato auditivo externo. Posición anatómica de la cabeza.', color:'#6366f1', icono:'📐' },

// ── SISTEMA NERVIOSO ─────────────────────────────────
{ id:'fc7', modulo:'Sistema Nervioso', frente:'¿Cuáles son las 4 divisiones del SNC?', reverso:'1. Cerebro (telencéfalo + diencéfalo)\n2. Cerebelo\n3. Tronco encefálico (mesencéfalo, protuberancia, bulbo)\n4. Médula espinal', color:'#8b5cf6', icono:'🧠' },
{ id:'fc8', modulo:'Sistema Nervioso', frente:'¿Cuál es la función del cerebelo?', reverso:'Coordinación de movimientos finos, equilibrio y postura.\nNO inicia movimientos: los AJUSTA.\nLesión → ataxia (pérdida de coordinación).', color:'#8b5cf6', icono:'🧠' },
{ id:'fc9', modulo:'Sistema Nervioso', frente:'¿Qué contiene la sustancia gris de la médula espinal?', reverso:'Cuerpos celulares de neuronas.\nEn forma de mariposa o H en el centro.\nAstas anteriores = motoras; Astas posteriores = sensitivas.', color:'#8b5cf6', icono:'🧠' },
{ id:'fc10', modulo:'Sistema Nervioso', frente:'¿Cuál es la diferencia entre el SN simpático y parasimpático?', reverso:'SIMPÁTICO: "lucha o huida" → ↑FC, dilata pupilas, ↓digestión. Neurotransmisor: noradrenalina.\nPARASIMPÁTICO: "reposo y digestión" → ↓FC, contrae pupilas, ↑digestión. Neurotransmisor: acetilcolina.', color:'#8b5cf6', icono:'🧠' },
{ id:'fc11', modulo:'Sistema Nervioso', frente:'¿Qué produce el área de Broca?', reverso:'Área de Broca (lóbulo frontal izquierdo) = producción del HABLA.\nLesión → afasia de Broca: entiende pero no puede hablar fluido.\nÁrea de Wernicke = comprensión del lenguaje.', color:'#8b5cf6', icono:'🧠' },
{ id:'fc12', modulo:'Sistema Nervioso', frente:'¿Cuál es la ley del todo o nada en el potencial de acción?', reverso:'Un estímulo subliminal no genera potencial de acción.\nSi supera el umbral, el potencial de acción se genera con la MISMA magnitud siempre.\nLa intensidad se codifica por FRECUENCIA, no por amplitud.', color:'#8b5cf6', icono:'🧠' },

// ── SISTEMA CARDIOVASCULAR ───────────────────────────
{ id:'fc13', modulo:'Sistema Cardiovascular', frente:'¿Cuál es la ruta del flujo sanguíneo en el corazón?', reverso:'VCS/VCI → Aurícula derecha → Válvula tricúspide → Ventrículo derecho → Válvula pulmonar → Pulmones → Venas pulmonares → Aurícula izquierda → Válvula mitral → Ventrículo izquierdo → Válvula aórtica → Aorta', color:'#ef4444', icono:'❤️' },
{ id:'fc14', modulo:'Sistema Cardiovascular', frente:'¿Cuál es la fórmula del gasto cardíaco?', reverso:'GC = Volumen Sistólico × Frecuencia Cardíaca\nVS normal: ~70 mL/latido\nFC normal: 70 lat/min\nGC normal en reposo: ~5 L/min\nEn ejercicio puede llegar a 25 L/min', color:'#ef4444', icono:'❤️' },
{ id:'fc15', modulo:'Sistema Cardiovascular', frente:'¿Qué es la presión arterial normal?', reverso:'120/80 mmHg\n120 = sistólica (contracción ventricular)\n80 = diastólica (relajación ventricular)\nHipertensión: ≥140/90 mmHg\nHipotensión: <90/60 mmHg', color:'#ef4444', icono:'❤️' },
{ id:'fc16', modulo:'Sistema Cardiovascular', frente:'¿Qué capas tiene el corazón?', reverso:'Pericardio (saco externo) → Epicardio (capa visceral del pericardio) → Miocardio (músculo cardíaco) → Endocardio (capa interna).\nEl miocardio es la capa más gruesa.', color:'#ef4444', icono:'❤️' },
{ id:'fc17', modulo:'Sistema Cardiovascular', frente:'¿Qué diferencia arteria de vena?', reverso:'ARTERIA: lleva sangre DEL corazón. Paredes gruesas, musculares. Pulso palpable.\nVENA: lleva sangre AL corazón. Paredes delgadas. Tienen válvulas. Contienen el 70% de la sangre corporal.\nExcepción: venas pulmonares (sangre oxigenada) y arteria pulmonar (desoxigenada).', color:'#ef4444', icono:'❤️' },

// ── SISTEMA RESPIRATORIO ─────────────────────────────
{ id:'fc18', modulo:'Sistema Respiratorio', frente:'¿Cuál es el orden de la vía aérea superior a inferior?', reverso:'Nariz/Boca → Faringe → Laringe → Tráquea → Bronquios principales → Bronquios lobares → Bronquiolos → Alvéolos', color:'#38bdf8', icono:'🫁' },
{ id:'fc19', modulo:'Sistema Respiratorio', frente:'¿Dónde y cómo ocurre el intercambio gaseoso (hematosis)?', reverso:'En los ALVÉOLOS.\nO₂ pasa de alveolo → sangre (por difusión, mayor PO₂ alveolar).\nCO₂ pasa de sangre → alveolo (mayor PCO₂ en sangre).\nMembrana alveolocapilar = barrera de intercambio.', color:'#38bdf8', icono:'🫁' },
{ id:'fc20', modulo:'Sistema Respiratorio', frente:'¿Qué es el surfactante pulmonar y quién lo produce?', reverso:'Mezcla de fosfolípidos (principalmente DPPC) que reduce la tensión superficial alveolar evitando el colapso.\nProducido por: neumocitos tipo II\nDéficit en prematuros → síndrome de dificultad respiratoria neonatal.', color:'#38bdf8', icono:'🫁' },
{ id:'fc21', modulo:'Sistema Respiratorio', frente:'¿Qué músculos actúan en la inspiración normal vs forzada?', reverso:'NORMAL: solo el DIAFRAGMA (baja) y músculos intercostales externos.\nFORZADA: + escalenos, esternocleidomastoideo, pectorales.\nEspiración normal es PASIVA (elástica).\nEspiración forzada usa intercostales internos y abdominales.', color:'#38bdf8', icono:'🫁' },

// ── SISTEMA ENDOCRINO ────────────────────────────────
{ id:'fc22', modulo:'Sistema Endocrino', frente:'¿Cuál es la diferencia entre hormona peptídica y esteroide?', reverso:'PEPTÍDICA (ej: insulina, GH): no cruza membrana → actúa en receptor de superficie → segundo mensajero (AMPc). Acción rápida.\nESTEROIDEA (ej: cortisol, estrógeno): liposoluble, cruza membrana → actúa en receptor intracelular → modifica transcripción génica. Acción lenta pero duradera.', color:'#10b981', icono:'⚗️' },
{ id:'fc23', modulo:'Sistema Endocrino', frente:'¿Cuáles son las hormonas de la hipófisis anterior?', reverso:'GH (crecimiento), TSH (tiroides), ACTH (suprarrenal), FSH y LH (gonadales), PRL (prolactina).\nMnemotecnia: "GTA FSH" o "Gordo Tenía Sus Fantasías Locas Prolíficas"', color:'#10b981', icono:'⚗️' },
{ id:'fc24', modulo:'Sistema Endocrino', frente:'¿Qué hace la insulina vs el glucagón?', reverso:'INSULINA (células β, post-prandial): ↓glucemia → capta glucosa, sintetiza glucógeno y lípidos. ANABÓLICA.\nGLUCAGÓN (células α, ayuno): ↑glucemia → glucogenólisis + gluconeogénesis. CATABÓLICA.\nSon antagonistas.', color:'#10b981', icono:'⚗️' },
{ id:'fc25', modulo:'Sistema Endocrino', frente:'¿Cuáles son los signos de hipoglucemia?', reverso:'Con glucosa <70 mg/dL:\nSudoración, temblor, taquicardia (simpáticos)\n+ Confusión, cefalea, convulsiones (neuroglucopénicos)\nTratamiento: 15g de carbohidratos de absorción rápida (jugos, glucosa)', color:'#10b981', icono:'⚗️' },

// ── APARATO DIGESTIVO ────────────────────────────────
{ id:'fc26', modulo:'Aparato Digestivo', frente:'¿En qué parte del intestino ocurre la mayor absorción?', reverso:'INTESTINO DELGADO (principalmente yeyuno).\nTiene vellosidades y microvellosidades (borde en cepillo) que aumentan x600 el área de absorción.\nLongitud total: 6-7 metros.\nTambién se absorbe: vitamina B12 en íleon, agua en colon.', color:'#f59e0b', icono:'🫀' },
{ id:'fc27', modulo:'Aparato Digestivo', frente:'¿Cuáles son las 3 enzimas pancreáticas principales?', reverso:'LIPASA: digiere grasas (triglicéridos → ácidos grasos + glicerol)\nAMILASA: digiere almidón → maltosa\nPROTEASAS (tripsina, quimotripsina): digieren proteínas\nSe secretan como ZIMÓGENOS inactivos (se activan en duodeno por enteroquinasa).', color:'#f59e0b', icono:'🫀' },
{ id:'fc28', modulo:'Aparato Digestivo', frente:'¿Para qué sirve la bilis?', reverso:'Producida por HÍGADO, almacenada en VESÍCULA BILIAR.\nFunción: EMULSIFICACIÓN de grasas (las convierte en gotas pequeñas para que actúe la lipasa).\nContiene: sales biliares, bilirrubina, colesterol.\nSe libera por acción de la CCK (colecistocinina) tras ingerir grasas.', color:'#f59e0b', icono:'🫀' },

// ── BIOLOGÍA CELULAR ─────────────────────────────────
{ id:'fc29', modulo:'Biología Celular', frente:'¿Cuáles son los organelos de la célula eucariota?', reverso:'Membrana plasmática, Núcleo (con nucléolo), Mitocondria (ATP), Ribosoma (proteínas), RE rugoso (secreción), RE liso (lípidos), Ap. Golgi (empaque), Lisosoma (digestión), Centrosoma (división), Vacuola.', color:'#a78bfa', icono:'🔬' },
{ id:'fc30', modulo:'Biología Celular', frente:'¿Cuál es la diferencia entre mitosis y meiosis?', reverso:'MITOSIS: 1 célula → 2 células idénticas (2n→2n). Para crecimiento y reparación.\nMEIOSIS: 1 célula → 4 gametos con la mitad de cromosomas (2n→n=23). Para reproducción. Genera variabilidad genética por crossing-over.', color:'#a78bfa', icono:'🔬' },
{ id:'fc31', modulo:'Biología Celular', frente:'¿Qué es la mitocondria y por qué es especial?', reverso:'Orgánulo productor de ATP (energía celular) mediante respiración aerobia.\nTiene su PROPIO ADN (herencia materna).\nMembrana interna forma crestas donde está la cadena de transporte de electrones.\nCélulas con alta demanda energética tienen más mitocondrias.', color:'#a78bfa', icono:'🔬' },
{ id:'fc32', modulo:'Biología Celular', frente:'¿Qué es la replicación del ADN?', reverso:'Proceso de copia del ADN antes de la división celular.\nSemidiscontinua: una cadena se copia continua (líder) y otra discontinua (fragmentos de Okazaki).\nEnzima clave: ADN polimerasa (solo añade en dirección 5\'→3\').\nAntiparalela: si una cadena es 3\'→5\', la nueva es 5\'→3\'.', color:'#a78bfa', icono:'🔬' },

// ── CARBOHIDRATOS ────────────────────────────────────
{ id:'fc33', modulo:'Carbohidratos', frente:'¿Cuál es la función principal de los carbohidratos?', reverso:'ENERGÉTICA: fuente primaria y más rápida de energía.\n1g carbohidrato = 4 kcal.\nGlucosa = combustible preferido del cerebro y eritrocitos.\nTambién: estructural (celulosa, quitina), señalización (glicoproteínas), ahorro de proteínas.', color:'#f59e0b', icono:'🍬' },
{ id:'fc34', modulo:'Carbohidratos', frente:'¿Qué son los carbohidratos complejos vs simples?', reverso:'SIMPLES (azúcares): 1-2 monosacáridos. Absorción rápida → pico glucémico. Ej: glucosa, fructosa, sacarosa, lactosa.\nCOMPLEJOS (polisacáridos): muchos monosacáridos. Absorción lenta → glucemia estable. Ej: almidón, glucógeno, fibra.', color:'#f59e0b', icono:'🍬' },
{ id:'fc35', modulo:'Carbohidratos', frente:'¿Qué es el índice glucémico?', reverso:'Medida de qué tan rápido un alimento eleva la glucosa en sangre comparado con la glucosa pura (IG=100).\nALTO IG (>70): arroz blanco, pan blanco, azúcar → pico glucémico rápido.\nBAJO IG (<55): legumbres, avena → elevación lenta y sostenida.\nImportante en DM y nutrición deportiva.', color:'#f59e0b', icono:'🍬' },

// ── CONCEPTOS SALUD ──────────────────────────────────
{ id:'fc36', modulo:'Conceptos Salud', frente:'¿Cuáles son los niveles de prevención en salud?', reverso:'PRIMARIA: evitar que aparezca la enfermedad (vacunas, saneamiento).\nSECUNDARIA: detectar temprano y tratar (tamizajes, diagnóstico precoz).\nTERCIARIA: reducir daño y rehabilitar al enfermo (fisioterapia, diálisis).\nCUATERNARIA: evitar iatrogenias (sobrediagnóstico, sobretreatment).', color:'#14b8a6', icono:'🛡️' },
{ id:'fc37', modulo:'Conceptos Salud', frente:'¿Qué es la epidemiología y sus medidas básicas?', reverso:'Ciencia que estudia distribución y determinantes de enfermedades.\nINCIDENCIA = casos NUEVOS / población en riesgo (mide riesgo de enfermar).\nPREVALENCIA = todos los casos existentes / población total (mide carga de enfermedad).\nPrevalencia ≈ Incidencia × Duración de la enfermedad.', color:'#14b8a6', icono:'🛡️' },
{ id:'fc38', modulo:'Conceptos Salud', frente:'¿Cuáles son los determinantes de la salud de Lalonde?', reverso:'1. BIOLOGÍA HUMANA: genética, envejecimiento (~20%)\n2. MEDIO AMBIENTE: físico, social, psicológico (~20%)\n3. ESTILO DE VIDA: tabaco, alcohol, ejercicio (~50%)\n4. SISTEMA DE SALUD: atención médica (~10%)\nEl estilo de vida es el determinante más modificable.', color:'#14b8a6', icono:'🛡️' },
];

console.log(`✅ Flashcards cargadas: ${FLASHCARDS_DATA.length} tarjetas`);
